# A hook to build the build.
# - it creates .mobi, .epub and .pdf versions
# - these are available as a download as build artifacts

image: avastmick/ebook-builder:latest

before_script:
  - env

draft-job:
  stage: build
  script:
    - gitbook install
    - gitbook mobi ./ ./consensus-draft-$(date +"%m-%d-%y").mobi
    - gitbook epub ./ ./consensus-draft-$(date +"%m-%d-%y").epub
    - gitbook pdf ./ ./consensus-draft-$(date +"%m-%d-%y").pdf
  artifacts:
    paths:
      - ./*.mobi
      - ./*.epub
      - ./*.pdf
  only:
    - tags
    - draft
  tags:
    - shared
