# A hook to build the build.
# - should create .mobi, .epub and .pdf versions
# 

image: avastmick/ebook-builder:latest

before_script:
  - env

stages:
  - build

ebook:
  stage: build
  script:
    - gitbook mobi ./ ./consensus-draft-$(date +"%m-%d-%y").mobi
    - gitbook epub ./ ./consensus-draft-$(date +"%m-%d-%y").epub
    - gitbook pdf ./ ./consensus-draft-$(date +"%m-%d-%y").pdf
  artifacts:
    paths:
      - ./*.mobi
      - ./*.epub
      - ./*.pdf
  only:
    - draft
    # - tags
  tags:
    - shared
