# A hook to build the build.
# - should create .mobi, .epub and .pdf versions
# 

image: avastmick/ebook-builder:latest

before_script:
  - env

variables:
  DRAFT-FILE-NAME: consensus-draft-

stages:
  - build

ebook:
  stage: build
  script:
    - gitbook mobi
  artifacts:
    paths:
      - consensus-draft-$(date +"%m-%d-%y").mobi
  only:
    - draft
  tags:
    - shared
