# A hook to build the build.
# - it creates .mobi, .epub and .pdf versions
# - these are available as a download as build artifacts

image: avastmick/ebook-builder:pandoc

before_script:
  - env

draft-job:
  stage: build
  script:
    - pandoc -S --toc-depth=1 -o consensus-draft-$(date +"%m-%d-%y").epub pandoc.md chapters/*.md
    - pandoc -S --toc-depth=1 -o consensus-draft-$(date +"%m-%d-%y").pdf pandoc.md chapters/*.md
    - pandoc -S --toc-depth=1 -o consensus-draft-$(date +"%m-%d-%y").docx pandoc.md chapters/*.md
    - kindlegen *.epub
  artifacts:
    paths:
      - ./*.mobi
      - ./*.epub
      - ./*.pdf
      - ./*.docx
  only:
    - tags
    - draft
  tags:
    - shared
