# Configuration file for the Publish.py script

#  General params
book-name: consensus
ext: .md

# epub
epub-frontmatter: epub-frontmatter.md
epub-endmatter: epub-endmatter.md
epub-ext: .epub

#  web
draftDir: draft
webLocation: /home/avastmick/repos/avastmick.io/content/book/consensus/chapters
web-frontmatter: web-frontmatter.md
web-endmatter: web-endmatter.md
firstFile: prologue
fileNameBase: chapter
endmatter-title: "Read More..."

#  Do not change!
publishDir: publish
sourceDir: chapters
